--1.
CREATE TABLE ORDERS (
     ORDER_ID NUMBER(12,0)
    ,ORDER_DATE DATE
    ,ORDER_MODE VARCHAR2(8 BYTE)
    ,CUSTOMER_ID NUMBER(6,0)
    ,ORDER_STATUS NUMBER(2,0)
    ,ORDER_TOTAL NUMBER(8,2) DEFAULT 0
    ,SALES_REP_ID NUMBER(6,0)
    ,PROMOTION_ID NUMBER(6,0)
    ,constraint PK_ORDER primary key (ORDER_ID)
    ,constraint CK_ORDER_MODE check(ORDER_MODE in ('direct','online'))
);


--2.
CREATE TABLE ORDER_ITEMS (
     ORDER_ID NUMBER(12,0)
    ,LINE_ITEM_ID NUMBER(3,0)
    ,PRODUCT_ID NUMBER(3,0)
    ,UNIT_PRICE NUMBER(8,2) DEFAULT 0
    ,QUANTITY NUMBER(8,0) DEFAULT 0
    ,CRATE_DT DATE DEFAULT sysdate
    ,CONSTRAINT PK_ORDER_ITEMS primary key (ORDER_ID, LINE_ITEM_ID)
);

    
    
    
